// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { car as jaJP_car } from "./ja-JP";
import { starter as jaJP_starter } from "./ja-JP";
import { car as koKR_car } from "./ko-KR";
import { starter as koKR_starter } from "./ko-KR";
import { car as zhTW_car } from "./zh-TW";
import { starter as zhTW_starter } from "./zh-TW";
import { car as frFR_car } from "./fr-FR";
import { starter as frFR_starter } from "./fr-FR";
import { car as deDE_car } from "./de-DE";
import { starter as deDE_starter } from "./de-DE";
import { car as esES_car } from "./es-ES";
import { starter as esES_starter } from "./es-ES";
import { car as ptBR_car } from "./pt-BR";
import { starter as ptBR_starter } from "./pt-BR";
import { car as ruRU_car } from "./ru-RU";
import { starter as ruRU_starter } from "./ru-RU";
import { car as itIT_car } from "./it-IT";
import { starter as itIT_starter } from "./it-IT";
import { car as nlNL_car } from "./nl-NL";
import { starter as nlNL_starter } from "./nl-NL";
import { car as trTR_car } from "./tr-TR";
import { starter as trTR_starter } from "./tr-TR";
import { car as plPL_car } from "./pl-PL";
import { starter as plPL_starter } from "./pl-PL";
import { car as viVN_car } from "./vi-VN";
import { starter as viVN_starter } from "./vi-VN";
import { car as thTH_car } from "./th-TH";
import { starter as thTH_starter } from "./th-TH";
import { car as idID_car } from "./id-ID";
import { starter as idID_starter } from "./id-ID";
import { car as arEG_car } from "./ar-EG";
import { starter as arEG_starter } from "./ar-EG";
import { car as csCZ_car } from "./cs-CZ";
import { starter as csCZ_starter } from "./cs-CZ";
import { car as heIL_car } from "./he-IL";
import { starter as heIL_starter } from "./he-IL";
import { car as hiIN_car } from "./hi-IN";
import { starter as hiIN_starter } from "./hi-IN";
import { car as svSE_car } from "./sv-SE";
import { starter as svSE_starter } from "./sv-SE";
import { car as ukUA_car } from "./uk-UA";
import { starter as ukUA_starter } from "./uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "car": {
    "ja-JP": jaJP_car,
    "ko-KR": koKR_car,
    "zh-TW": zhTW_car,
    "fr-FR": frFR_car,
    "de-DE": deDE_car,
    "es-ES": esES_car,
    "pt-BR": ptBR_car,
    "ru-RU": ruRU_car,
    "it-IT": itIT_car,
    "nl-NL": nlNL_car,
    "tr-TR": trTR_car,
    "pl-PL": plPL_car,
    "vi-VN": viVN_car,
    "th-TH": thTH_car,
    "id-ID": idID_car,
    "ar-EG": arEG_car,
    "cs-CZ": csCZ_car,
    "he-IL": heIL_car,
    "hi-IN": hiIN_car,
    "sv-SE": svSE_car,
    "uk-UA": ukUA_car,
  },
  "starter": {
    "ja-JP": jaJP_starter,
    "ko-KR": koKR_starter,
    "zh-TW": zhTW_starter,
    "fr-FR": frFR_starter,
    "de-DE": deDE_starter,
    "es-ES": esES_starter,
    "pt-BR": ptBR_starter,
    "ru-RU": ruRU_starter,
    "it-IT": itIT_starter,
    "nl-NL": nlNL_starter,
    "tr-TR": trTR_starter,
    "pl-PL": plPL_starter,
    "vi-VN": viVN_starter,
    "th-TH": thTH_starter,
    "id-ID": idID_starter,
    "ar-EG": arEG_starter,
    "cs-CZ": csCZ_starter,
    "he-IL": heIL_starter,
    "hi-IN": hiIN_starter,
    "sv-SE": svSE_starter,
    "uk-UA": ukUA_starter,
  },
};
