import type { ReactNode } from "react";

export type FieldKind =
  | "text"
  | "textarea"
  | "number"
  | "date"
  | "datetime"
  | "select"
  | "relation"
  | "attachment";

export type RelationOption = {
  resource: string;
  labelField: string;
  idField?: string;
  subFields?: string[];
};

export type CarFieldConfig = {
  name: string;
  title: string;
  kind: FieldKind;
  required?: boolean;
  options?: { value: string; label: string }[];
  relation?: RelationOption;
  /** Backend auto-generates this value (e.g. a sequence number). Hidden from edit. */
  autoGenerated?: boolean;
};

export type CarColumnFieldRef = {
  accessor: string;
  kind?: "text" | "number" | "date" | "datetime" | "select" | "relation" | "attachment";
  options?: { value: string; label: string }[];
  relation?: RelationOption;
  label?: string;
  priority?: "primary" | "secondary";
};

export type CarColumnConfig = {
  accessor: string;
  header: string;
  sortable?: boolean;
  size?: number;
  kind?: "text" | "number" | "date" | "datetime" | "select" | "relation" | "attachment";
  options?: { value: string; label: string }[];
  relation?: RelationOption;
  render?: (record: Record<string, unknown>) => ReactNode;
  /** When set, renders multiple fields stacked in one column. */
  composite?: CarColumnFieldRef[];
  /** Make the cell open the record detail on click. Defaults true for non-action columns. */
  clickable?: boolean;
};

export type CarRelatedConfig = {
  resource: string;
  titleKey: string;
  filterField: string;
  columns: CarColumnConfig[];
  canCreate?: boolean;
  canDelete?: boolean;
};

export type CarResourceConfig = {
  name: string;
  titleKey: string;
  descriptionKey: string;
  icon: ReactNode;
  priority: number;
  group?: string;
  fields: CarFieldConfig[];
  columns: CarColumnConfig[];
  searchableFields?: string[];
  related?: CarRelatedConfig[];
  view?: "table" | "kanban" | "cards" | "calendar";
  boardField?: string;
  boardOptions?: { value: string; label: string }[];
  boardTitle?: string;
  boardSubtitle?: string[];
  cardTitle?: string;
  cardSubtitle?: string[];
  cardBadge?: string;
  cardBadgeOptions?: { value: string; label: string }[];
  calendarField?: string;
  calendarEndField?: string;
  /** Relation or plain field used as the calendar event title, e.g. "vehicle". */
  calendarTitleField?: string;
  canCreate?: boolean;
  canDelete?: boolean;
  /** Configures an embedded AI assistant rendered below the resource list. */
  aiAssistant?: {
    kind: "scm_dispatch" | "contract" | "pricing";
    titleKey: string;
    descriptionKey: string;
  };
  /** Configures an AI shortcut shown on the record detail page. */
  aiShow?: {
    kind: "contract" | "pricing";
    titleKey: string;
    descriptionKey: string;
    shortcutLabelKey: string;
  };
};
